[project]
authors = [{name = "Vincent Lee", email = "lws.vincent@hotmail.com"}] 
description = "report generator for python version, but dll is construct from report gen C# project" # å¥—ä»¶æè¿°
# license = {file = "LICENSE"}# æˆæ¬Šå”è­° 
name = "Report_Generator_PY" # å¥—ä»¶åç¨± (èˆ‡ `pip install` åç¨±ä¸€è‡´)
readme = "README.md" # è®€å–èªªæ˜æ–‡ä»¶
requires-python = ">=3.8" # æ”¯æ´çš„ Python ç‰ˆæœ¬
version = "0.1.0" # ç‰ˆæœ¬è™Ÿ (Semantic Versioning)

# ğŸ“Œ [3] ä¾è³´ (æœƒè‡ªå‹•å®‰è£)
dependencies = []
